/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./app/**/*.{js,ts,jsx,tsx,mdx}'],
  darkMode: 'class',
  theme: {
    screens: {
      tablet: '640px',
      desktop: '1024px',
      lgDesktop: '1200px',
    },
    colors: {
      white: '#ffffff',
      black: '#000000',
      light: '#d0dbdd',
      sand: '#e0c2a0',
      blue: '#98c0d9',
      fuchsia: '#b76ca4',
      dark: '#293241',
      mint: '#9adbba',
      papaya: '#ffa266',
      coral: '#ff6f61',
      current: 'currentColor',
    },
    fontFamily: {
      sans: ['Montserrat', 'sans-serif'],
      title: ['Montserrat Alternates', 'sans-serif'],
      blog: ['Dancing Script', 'cursive'],
    },
    extend: {
      typography: ({ theme }) => ({
        ocobo: {
          css: {
            '--tw-prose-body': theme('colors.dark'),
            '--tw-prose-headings': theme('colors.dark'),
            '--tw-prose-lead': theme('colors.dark'),
            '--tw-prose-links': theme('colors.coral'),
            '--tw-prose-bold': theme('colors.dark'),
            '--tw-prose-counters': theme('colors.dark'),
            '--tw-prose-bullets': theme('colors.mint'),
            '--tw-prose-hr': theme('colors.light'),
            '--tw-prose-quotes': theme('colors.blue'),
            '--tw-prose-quote-borders': theme('colors.mint'),
            '--tw-prose-captions': theme('colors.pink[700]'),
            '--tw-prose-code': theme('colors.dark'),
            '--tw-prose-pre-code': theme('colors.dark'),
            '--tw-prose-pre-bg': theme('colors.light'),
            '--tw-prose-th-borders': theme('colors.dark'),
            '--tw-prose-td-borders': theme('colors.dark'),
            '--tw-prose-invert-body': theme('colors.light'),
            '--tw-prose-invert-headings': theme('colors.light'),
            '--tw-prose-invert-lead': theme('colors.light'),
            '--tw-prose-invert-links': theme('colors.coral'),
            '--tw-prose-invert-bold': theme('colors.light'),
            '--tw-prose-invert-counters': theme('colors.pink[400]'),
            '--tw-prose-invert-bullets': theme('colors.mint'),
            '--tw-prose-invert-hr': theme('colors.light'),
            '--tw-prose-invert-quotes': theme('colors.blue'),
            '--tw-prose-invert-quote-borders': theme('colors.mint'),
            '--tw-prose-invert-captions': theme('colors.light'),
            '--tw-prose-invert-code': theme('colors.light'),
            '--tw-prose-invert-pre-code': theme('colors.light'),
            '--tw-prose-invert-pre-bg': 'rgb(0 0 0 / 50%)',
            '--tw-prose-invert-th-borders': theme('colors.light'),
            '--tw-prose-invert-td-borders': theme('colors.light'),
          },
        },
      }),
    },
  },
  plugins: [require('@tailwindcss/typography')],
};
