export const url = {
  homepage: '/',
  strategy: '/strategies-revenue-operations',
  projects: '/projets-revops',
  stories: '/stories',
  about: '/about',
  careers: '/careers',
  news: '/news',
  webinars: '/webinars',
  blog: '/blog',
  tools: '/tools',
  contact: '/contact',
  privacy: '/privacy',
  notFound: '/404',
};
